---
html_document: default
author: "Hao Guo Wentao Lu JiaoZhe Zhang"
date: "05/06/2022"
title: "NYC Taxi"
---

Using the tidyverse because it has the libraries to clean, mutate and visualize data. library(data.table) - helps load data faster then read csv

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table)
library(lubridate)
library(magrittr)
library(flexdashboard)
library(ggrepel)
library(formattable)
library(sf)
library(plotly)
library(treemapify)
library(scales)
library(RColorBrewer)
library(formatR)
library(caret)
library(rgdal)
```

```{r}
taxi_data_join_4=fread('clean_data_haoguo.csv')
```

## Column {data-width="500"}

### Avg Fare

```{r}
valueBox(scales::dollar(12.32), icon ="fas fa-taxi", color = "black")
```

### Avg Distance

```{r}
Withtext <- dollar_format(prefix = " ",suffix=" Miles")
valueBox(Withtext(2.87), icon = "fas fa-taxi", color = "black")
```

### Avg Duration

```{r}
Withtext <- dollar_format(prefix = " ",suffix=" Minutes")
valueBox(Withtext(35), icon = "fas fa-taxi", color = "black")
#Change to show avg distance instead of trips this week
```

### Busiest Days

```{r, fig.width=42, fig.height=16}
taxi_data_join_4  %>%
  ggplot(aes(x = weekday)) + geom_bar(fill = '#FFF0F5') + ylab("Number of Rides") + xlab("Weekday") + scale_x_discrete(
    limits = c(
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday"
    )
  ) + ylab("Number of Rides") + xlab("Weekday") + scale_y_continuous(labels = comma) + theme(axis.text = element_text(size = 50),
                                                                                             axis.title = element_text(size = 50)) + theme(
                                                                                               panel.grid.major = element_blank(),
                                                                                               panel.grid.minor = element_blank(),
                                                                                               panel.background = element_blank(),
                                                                                               axis.line = element_line(colour = "black")
                                                                                             ) +  theme(plot.background = element_rect(fill = 'white', colour = 'black'))

```

### Busiest Times

```{r, fig.width=42, fig.height=16}
ggplot(data = taxi_data_join_4, aes(x = hour)) + geom_bar(fill = '#FFF0F5') + scale_x_continuous(breaks =
                                                                                                   seq(0, 30)) + ylab("Number of Rides") + xlab("Hour") + scale_y_continuous(labels = comma) + theme(axis.text = element_text(size = 50),
                                                                                                                                                                                                     axis.title = element_text(size = 50)) + theme(
                                                                                                                                                                                                       panel.grid.major = element_blank(),
                                                                                                                                                                                                       panel.grid.minor = element_blank(),
                                                                                                                                                                                                       panel.background = element_blank(),
                                                                                                                                                                                                       axis.line = element_line(colour = "black")
                                                                                                                                                                                                     ) +  theme(plot.background = element_rect(fill = 'white', colour = 'black'))


```

## Column {.tabset} fig.width=50

### Most popular pick-up locations

```{r fig.height=16, fig.width=42, warning=FALSE}
taxi_data_join_4 %>%
  ggplot(aes(x = PU_borough)) + geom_bar(fill = '#FFF0F5') + coord_flip() +
  scale_y_continuous(labels = comma) + xlab("Top Pick-Up Locations") +  ylab("Number of Rides") + scale_x_discrete(limits = c(
"EWR",
                                                                                                                              
"Bronx",
                                                                                                                              "Queens",
                                                                                                                              "Brooklyn",
                                                                                                                              "Manhattan")) + theme(axis.text = element_text(size = 50),
                                                                                                                                                    axis.title = element_text(size = 50)) + theme(
                                                                                                                                                      panel.grid.major = element_blank(),
                                                                                                                                                      panel.grid.minor = element_blank(),
                                                                                                                                                      panel.background = element_blank(),
                                                                                                                                                      axis.line = element_line(colour = "black")
                                                                                                                                                    ) +  theme(plot.background = element_rect(fill = 'white', colour = 'black'))



 
```

### Most popular drop-off locations

```{r fig.height=16, fig.width=42, warning=FALSE}
taxi_data_join_4 %>%
  ggplot(aes(x = DO_borough)) + geom_bar(fill = '#FFF0F5') + coord_flip() +
  scale_y_continuous(labels = comma) + xlab("Top Drop Off Locations") +  ylab("Number of Rides") + scale_x_discrete(limits = c(
"EWR",
                                                                                                                              
"Bronx",
                                                                                                                              "Queens",
                                                                                                                              "Brooklyn",
                                                                                                                              "Manhattan")) + theme(axis.text = element_text(size = 50),
                                                                                                                                                    axis.title = element_text(size = 50)) + theme(
                                                                                                                                                      panel.grid.major = element_blank(),
                                                                                                                                                      panel.grid.minor = element_blank(),
                                                                                                                                                      panel.background = element_blank(),
                                                                                                                                                      axis.line = element_line(colour = "black")
                                                                                                                                                    ) +  theme(plot.background = element_rect(fill = 'white', colour = 'black'))
```

```{r}
M=taxi_data_join_4 %>% 
    filter(taxi_data_join_4$PU_borough=='Manhattan')
```

```{r}
library(treemap)
count_weekday=M%>%
                  select(weekday) %>%
                  group_by(weekday) %>%
                  summarize(count = n())

count_weekday <- data.table(count_weekday)


count_weekday <- count_weekday[is.na(weekday)  ==  FALSE, ]

count_weekday <- data.frame(count_weekday)

tm <- treemap(count_weekday , index = c("weekday"),
              vSize = "count")
```

```{r}
na.omit(M)
```

```{r}
lm_1 <- lm(fare_amount ~trip_distance+trip_hours, M)
a=varImp(lm_1,scale=TRUE)
a=setNames(cbind(rownames(a), a, row.names = NULL), 
         c("group", "value"))
a <- a %>% 
  arrange(desc(group)) %>%
  mutate(prop = value / sum(a$value) *1000) %>%
  mutate(ypos = cumsum(prop)- 0.5*prop )
ggplot(a, aes(x="", y=prop, fill=group)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  theme_void() + 
  theme(legend.position="none") +
  geom_text(aes(y = ypos, label = group), color = "white", size=6) +
  scale_fill_brewer(palette="Set1")
```

```{r}
my_spdf2 <- read_sf('taxi_zones_map.json')
plot(my_spdf2)

m=taxi_data_join_4 %>% filter(month_day=='21')%>%filter(dow=='1')%>%filter(hour=='12')
setnames(m, 'PU_zone', "zone")
M3=merge(m,my_spdf2,by='zone')
library(ggplot2)
ggplot(M3)+
  geom_sf(aes(fill= total_amount,geometry = geometry))+
  scale_fill_gradient(low= "#f1b8f1", high = "#ef5767")
```
